dataset: TKY
data_dir: datasets/TKY_v1
seed: 2023
distance_threshold: 2.5
num_epochs: 30
batch_size: 200
emb_dim: 128
lr: 0.001
decay: 0.0005
dropout: 0.3
deviceID: 0
lambda_cl: 0.1
lambda_mask: 0.05
num_mv_layers: 3
num_geo_layers: 3
num_di_layers: 3
num_tc_layers: 2
temperature: 0.1
keep_rate: 1.0
keep_rate_poi: 1.0
keep_rate_tc: 1.0
tc_weight_mode: log1p
beta_tc: 1.0
mask_rate: 0.2
mask_alpha: 2
lr_scheduler_factor: 0.1
save_dir: logs_v1
